site_name: Katarina Kajan
theme:
  name: material
  palette:
    primary: teal
  font:
    text: Roboto
    code: Ubuntu Sans Mono


extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/KatarinaKajan